### PR TITLE
arbitrary terminal size on launch

### PR DESCRIPTION
**Pull request by pavelskipenes**
removes hard-coded terminal dimentions. Needs to be tested on windows.

### CODE REVIEW

**Comment by pavelskipenes** [comment]
I got the information from here: https://stackoverflow.com/questions/23369503/get-size-of-terminal-window-rows-columns
I've tested on linux and it works fine. Needs to be tested on windows.

**Review by ErlingLie — APPROVED** [review]

**Comment by pavelskipenes** [comment]
Did it actually work on windows?

**Comment by pavelnoen94** [comment]
Did it work on windows?

**Comment by ErlingLie** [comment]
Did not test as the linux and windows versions are currently separated.

**Pull request merged**
